projects:
  database:
    schemaPath: prisma/prisma-types.graphql
    extensions:
      endpoints:
        default: http://localhost:4466
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: prisma/prisma.binding.ts
